import { useNavigate } from 'react-router-dom'
import PageContainer from '../components/layout/PageContainer.jsx'
import Button from '../components/common/Button.jsx'
import Icon from '../components/common/Icon.jsx'

const configs = {
  users: { title: 'Users', eyebrow: 'Identity', description: 'Manage people, credentials, roles, and account status.', add: 'Create user', addPath: '/users/new', columns: ['User', 'Status', 'Last active', 'Created'], rows: [['Jordan Miller', 'jordan.miller@acme.co', 'Active', '2 min ago', 'Sep 28, 2026'], ['Ava Kim', 'ava.kim@acme.co', 'Active', '18 min ago', 'Sep 24, 2026'], ['Ravi Shah', 'ravi.shah@acme.co', 'Invited', 'Never', 'Sep 19, 2026'], ['Lena Wu', 'lena.wu@acme.co', 'Active', '1 hr ago', 'Sep 12, 2026']] },
  roles: { title: 'Roles', eyebrow: 'Identity', description: 'Define access boundaries for teams and service accounts.', add: 'Create role', columns: ['Role', 'Members', 'Permissions', 'Updated'], rows: [['Administrator', '3 members', 'All permissions', 'Today'], ['Support agent', '12 members', '24 permissions', 'Yesterday'], ['Viewer', '48 members', '8 permissions', 'Sep 24, 2026']] },
  organizations: { title: 'Organizations', eyebrow: 'Identity', description: 'Multi-tenant organization management is planned for a later release.', columns: ['Organization', 'Members', 'Status', 'Created'], rows: [['Acme workspace', '64 members', 'Planned', 'October 2026']] },
  applications: { title: 'Applications', eyebrow: 'Access', description: 'Configure OAuth clients, redirect URIs, and authentication flows.', add: 'Create application', addPath: '/applications/new', columns: ['Application', 'Protocol', 'Status', 'Last used'], rows: [['Slack workspace', 'OIDC', 'Connected', '4 min ago'], ['Notion', 'OAuth 2.0', 'Connected', 'Yesterday'], ['Linear', 'OIDC', 'Needs setup', 'Never']] },
  'identity-providers': { title: 'Identity providers', eyebrow: 'Access', description: 'Connect trusted providers for federated sign-in.', add: 'Add provider', columns: ['Provider', 'Protocol', 'Status', 'Last sign-in'], rows: [['Google Workspace', 'OIDC', 'Connected', '12 min ago'], ['External provider', 'OIDC', 'Draft', 'Never']] },
  sessions: { title: 'Sessions', eyebrow: 'Monitoring', description: 'Review active sessions and terminate access when needed.', columns: ['User', 'Device', 'Location', 'Last active'], rows: [['Jordan Miller', 'Chrome on macOS', 'New York, US', '2 min ago'], ['Ava Kim', 'Safari on iPhone', 'Toronto, CA', '18 min ago']] },
  audit: { title: 'Audit logs', eyebrow: 'Monitoring', description: 'A searchable trail of security and identity events.', columns: ['Event', 'Actor', 'Resource', 'Time'], rows: [['User signed in', 'Jordan Miller', 'Passkey', '2 min ago'], ['Application updated', 'Jamie Doe', 'Linear', '42 min ago'], ['Role assigned', 'Jamie Doe', 'Support agent', '1 hr ago']] },
}

export default function ResourcePage({ type }) {
  const config = configs[type] || configs.users
  const navigate = useNavigate()
  return <PageContainer><section className="page-heading resource-heading"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p className="subheading">{config.description}</p></div>{config.add && <Button icon="plus" onClick={() => navigate(config.addPath || `/${type}/new`)}>{config.add}</Button>}</section><div className="filter-bar"><label className="search table-search"><Icon name="search" size={16} /><input placeholder={`Search ${config.title.toLowerCase()}`} /></label><div className="filter-actions"><button className="filter-button">All status <span>⌄</span></button><button className="filter-button">Filter <span>☷</span></button></div></div><section className="table-panel"><table><thead><tr>{config.columns.map((column) => <th key={column}>{column}</th>)}<th /></tr></thead><tbody>{config.rows.map((row, rowIndex) => <tr key={row[0]} onClick={() => type === 'users' && navigate(`/users/${rowIndex + 1}`)}>{row.map((cell, cellIndex) => <td key={`${row[0]}-${cell}`}><span className={cellIndex === 2 && ['Active', 'Connected'].includes(cell) ? 'table-name' : ''}>{cell}</span>{cellIndex === 0 && type === 'users' && <small className="table-sub">{row[1]}</small>}</td>)}<td><button className="row-arrow" aria-label={`Open ${row[0]}`}><Icon name="arrow" size={15} /></button></td></tr>)}</tbody></table></section></PageContainer>
}
